language: node_js
node_js:
  - "0.10"
before_script:
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm start &
  - webdriver-manager update
  - webdriver-manager start &
  - sleep 3
script:
  - ./node_modules/karma/bin/karma start tests/karma.conf.js
  - ./node_modules/.bin/protractor ./tests/e2e/conf.js --browser=firefox